services:
  bolt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7700:7700"
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - GROQ_API_KEY=${GROQ_API_KEY}
      # - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - VITE_LOG_LEVEL=debug
      - OLLAMA_API_BASE_URL=http://10.3.0.6:11434
    volumes:
      # This volume is for development purposes, allowing live code updates
      # Comment out or remove for production
      - .:/app
      # This volume is to prevent node_modules from being overwritten by the above volume
      - /app/node_modules
    command: pnpm run start

volumes:
  node_modules: